const PhotoshopFiles = [
  { src: "101.png", title: "Take a look!" },
  { src: "102.jpg", title: "Take a look!" },
  { src: "103.jpg", title: "Take a look!" },
  { src: "104.jpg", title: "Take a look!" },
  { src: "105.jpg", title: "Take a look!" },
  { src: "m1.jpg", title: "Take a look!" },
  { src: "m2.jpg", title: "Take a look!" },
  { src: "m3.jpg", title: "Take a look!" },
  { src: "m4.jpg", title: "Take a look!" },
  { src: "m5.jpg", title: "Take a look!" },
  { src: "m6.jpg", title: "Take a look!" },
  { src: "m8.png", title: "Take a look!" },
  { src: "m9.png", title: "Take a look!" },
  { src: "m10.png", title: "Take a look!" },
  { src: "m11.png", title: "Take a look!" },
  { src: "cb1.jpg", title: "Take a look!" },
  { src: "cb2.jpg", title: "Take a look!" },
  { src: "cb3.jpg", title: "Take a look!" },
  { src: "cb4.jpg", title: "Take a look!" },
  { src: "1.jpg", title: "Take a look!" },
  { src: "2.jpg", title: "Take a look!" },
  { src: "p1.jpg", title: "Take a look!" },
  { src: "p2.jpg", title: "Take a look!" },
  { src: "5.jpg", title: "Take a look!" },
  { src: "6.jpg", title: "Take a look!" },
  { src: "7.jpg", title: "Take a look!" },
  { src: "8.jpg", title: "Take a look!" },
  { src: "9.jpg", title: "Take a look!" },
  { src: "10.jpg", title: "Take a look!" },
  { src: "11.1.jpg", title: "Take a look!" },
  { src: "11.jpg", title: "Take a look!" },
  { src: "12.jpg", title: "Take a look!" },
  { src: "13.jpg", title: "Take a look!" },
  { src: "14.jpg", title: "Take a look!" },
  { src: "15.jpg", title: "Take a look!" },
  { src: "16.jpg", title: "Take a look!" },
  { src: "17.jpg", title: "Take a look!" },
  { src: "18.jpg", title: "Take a look!" },
  { src: "19.jpg", title: "Take a look!" },
  { src: "20.jpg", title: "Take a look!" },
  { src: "21.jpg", title: "Take a look!" },
  { src: "22.jpg", title: "Take a look!" },
  { src: "23.jpg", title: "Take a look!" },
  { src: "24.jpg", title: "Take a look!" },
  { src: "25.jpg", title: "Take a look!" },
  { src: "26.jpg", title: "Take a look!" },
  { src: "27.jpg", title: "Take a look!" },
  { src: "28.jpg", title: "Take a look!" },
  { src: "29.jpg", title: "Take a look!" },
  { src: "30.jpg", title: "Take a look!" },
  { src: "31.jpg", title: "Take a look!" },
  { src: "32.jpg", title: "Take a look!" },
  { src: "33.jpg", title: "Take a look!" },
  { src: "34.jpg", title: "Take a look!" },
  { src: "35.jpg", title: "Take a look!" },
  { src: "36.jpg", title: "Take a look!" },
  { src: "37.jpg", title: "Take a look!" },
  { src: "38.jpg", title: "Take a look!" },
  { src: "39.jpg", title: "Take a look!" },
  { src: "40.jpg", title: "Take a look!" },
  { src: "41.jpg", title: "Take a look!" },
  { src: "42.jpg", title: "Take a look!" },
  { src: "43.jpg", title: "Take a look!" },
  { src: "44.jpg", title: "Take a look!" },
  { src: "45.jpg", title: "Take a look!" },
  { src: "46.jpg", title: "Take a look!" },
  { src: "47.jpg", title: "Take a look!" },
  { src: "48.jpg", title: "Take a look!" },
];



const IllustratorFiles = [
  { src: 'I1.jpg', title: "Take a look!" },
  { src: 'I2.jpg', title: "Take a look!" },
  { src: 'I3.jpg', title: "Take a look!" },
  { src: 'I4.jpg', title: "Take a look!" },
  { src: 'I5.jpg', title: "Take a look!" },
  { src: 'I6.jpg', title: "Take a look!" },
  { src: 'I7.jpg', title: "Take a look!" },
]

const PPTFiles = [
  { src: 'PP1.jpg', title: "Take a look!" },
  { src: 'PP2.jpg', title: "Take a look!" },
  { src: 'PP3.jpg', title: "Take a look!" },

]


const videoFiles = [
  { src: 'A1_lensekart.mp4', title: 'Lensekart' },
  { src: 'A1_Phonepe_rework.mp4', title: 'Lensekart' },
  { src: 'A2.mp4', title: 'Lensekart' },
  { src: 'BG_CHARECTER ANIMATION.mp4', title: 'Lensekart' },
  { src: 'BOAT ANIMATION WITH SHAPES.mp4', title: 'Lensekart' },
  { src: 'INDIA MAP ANIMATION.mp4', title: 'Lensekart' },
  { src: 'Jan23_GP1_JK.mp4', title: 'Lensekart' },
  { src: 'Jan23_GP_JK4.mp4', title: 'Lensekart' },
  { src: 'Nityam.mp4', title: 'Lensekart' },
  { src: 'Nityam1.mp4', title: 'Lensekart' },
  { src: 'Nityam3.mp4', title: 'Lensekart' },
  { src: 'Nityam4.mp4', title: 'Lensekart' },
  { src: 'TEA CUP ANUMATION.mp4', title: 'Lensekart' },
  { src: 'UPSC.mp4', title: 'Lensekart' },
  { src: 'Vaishnavi.mp4', title: 'Lensekart' },
  { src: 'Vaishnavi2.mp4', title: 'Lensekart' },
  { src: 'Vaishnavi3.mp4', title: 'Lensekart' }
];